### ISSUE TITLE
support azure-openai gpt-35-turbo models

### ISSUE THREAD

**Issue by fcakyon** [jackschedel/gpt.koaladev.io#104]
Hey @jackschedel !

Thanks for the awesome repo!

Azure Openai models are named as 'gpt-35-turbo-1106' instead of 'gpt-3.5-turbo-1106'. Could you add a mapping for azure endpoints by checking the endpoint URL? Azure endpoints are in this format: 'https://DEPLOYMENT-NAME.openai.azure.com/'. 

Something like this would work: if 'openai.azure.com' in endpoint_url, change 'gpt-3.5-turbo-1106' to 'gpt-35-turbo-1106'.

Bests

**Comment by jackschedel** [comment]
Thanks for the kind words.
Actually already working on implementing custom model names + endpoint formats as of a few days ago xD

**Comment by fcakyon** [comment]
> Thanks for the kind words. Actually already working on implementing custom model names + endpoint formats as of a few days ago xD

Glad to hear! Will be waiting curiously 👀

**Comment by fcakyon** [comment]
@jackschedel any update on this? :)

**Comment by jackschedel** [comment]
@fcakyon still in progress. Development is occuring on the 2.1.0 branch.

**Comment by jackschedel** [comment]
In 2.1.0, you can custom-define model names + endpoints :)
