### ISSUE TITLE
make electron app not open links in electron window

### ISSUE THREAD

**Issue by jackschedel** [jackschedel/gpt.koaladev.io#21]
https://stackoverflow.com/questions/31749625/make-a-link-from-electron-open-in-browser

**Comment by cheeseonamonkey** [comment]
The top answer there is a bit outdated _(2015)_.

While `require("shell").openExternal("http://www.google.com")` would work fine, it could also be annoying to set up with unknown URLs _(links in chat messages)_ and in multiple places.

There is an electron setting, in the `webPreferences` parameter of the Electron function `createWindow` to open externally by default. The new code [here](https://github.com/jackschedel/gpt.koaladev.io/blob/e4b8f4672e1028586a78823c084bd5daff4a6c1d/electron/index.cjs#L38) might be something like:
```
  win = new BrowserWindow({
	  autoHideMenuBar: true,
    show: false,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      nativeWindowOpen: true // set to true to open links externally by default
    }
  });

```

**Comment by jackschedel** [comment]
@cheeseonamonkey thanks for the info. I've been really busy lately so I haven't been updating the app as much and wouldn't have gotten around to it in a while, so your comment definitely sped things up by a few weeks xD.

The change should be live on the latest release. https://github.com/jackschedel/gpt.koaladev.io/releases/tag/4cd8e6175cd804021c154f6da702cef2cc5fede8-5306093363 (I won't be able to verify that it works as intended until Monday tho)

Next time, feel free to submit a PR too.

**Comment by cheeseonamonkey** [comment]
@jackschedel
The original repo is a mess, and I like your improvements :) 

I have a couple more bugs in mind too, but I want to familiarize myself with Svelte first
