### ISSUE TITLE
SHIFT + ENTER behavior (when editing a message) 

### ISSUE THREAD

**Issue by cheeseonamonkey** [jackschedel/gpt.koaladev.io#26]
#  **`SHIFT` + `ENTER`** behavior when editing existing chat messages.

I am frequently editing _existing_ System/User/Assistant chat messages. It is a useful technique to:
- establish context 
- reduce API token usage _(cost)_
- "rewind" the conversation to a previous state, perhaps after a tangent

## Notice that:

- #### When composing a _NEW_ message:
  - Pressing just the **`ENTER`** key sends the message
  - **`SHIFT` + `ENTER`** creates a new line without sending the message.
    - *this is common already (e.g. Facebook Messenger, etc.), and many users will already intuitively understand it.*
- #### **However,** when editing an _EXISTING_ message:
  - Pressing just the **`ENTER`** key creates a new line
  -  **`SHIFT` + `ENTER`** will _send_ the message

---

>Because **`SHIFT` + `ENTER`** explicitly sends the HTTP request, it seems like this might've been deliberate by the original author? But I can't see any reason as to why!
>
>I've even been using a UserScript to accomplish this for a few weeks now, so I feel familiar with each UX.
>
 >But if there is a good reason for the inconsistency, it could be implemented as something that the user could toggle on or off, in the configuration settings.

**Comment by cheeseonamonkey** [comment]
Could label as bug

**Comment by jackschedel** [comment]
Current Behavior:

| Mode          | Key Pressed | "Enter to Submit" Checked       | "Enter to Submit" Not Checked   |
|---------------|-------------|-------------------------------|-------------------------------|
| Editing Mode  | Enter | New Line                      | New Line                      |
| Editing Mode  | Shift+Enter | New Line                      | New Line                      |
| Message Mode  | Enter       | Send Message                  | New Line    |
| Message Mode  | Shift+Enter | New Line          | New Line                      |

This isn't a bug per say, it is just how I configured it. I only ever use the "Enter to Submit" checked option. If you want, can adjust the nonchecked option, or add another one. If you could provide what you want in a table that'd be ideal.

Thinking about this issue, I think I should also add a radio checkbox for whether "Save and Submit" on Edit brings up a new confirmation box. (I'll make a new issue rn)
