### ISSUE TITLE
add keybind for model swap

### ISSUE THREAD

**Issue by jackschedel** [jackschedel/gpt.koaladev.io#29]

**Comment by cheeseonamonkey** [comment]
I have a basis for some simple keyboard shortcut stuff [**here**](https://github.com/cheeseonamonkey/chat.cheeseonamonkey/compare/main...cheeseonamonkey:chat.cheeseonamonkey:KeyboardShortcuts#diff-b01b87228c65c6a5513a58fcb785191a29c599d79256bcfe314958b171572f4fR1)

I have a few ideas for key bindings as well!

**Comment by jackschedel** [comment]
use example keybind from [added ctrl-e keybind to toggle side menu #22](https://github.com/jackschedel/gpt.koaladev.io/commit/e7c2b3fcfe38e22a87ffa8dcef0151cc60edf3fd)

**Comment by jackschedel** [comment]
gpt-4 turbo is so cheap there's no point imo
