### ISSUE TITLE
add Android .apk build

### ISSUE THREAD

**Issue by jackschedel** [jackschedel/gpt.koaladev.io#43]

**Comment by cheeseonamonkey** [comment]
I've tried a few ways to do this. Currently I use an Android App you make on gonative.io, and it works great for the most part.

~~But the possible option I came across to do this ourselves was called [Cordova](https://cordova.apache.org/docs/en/11.x/guide/cli/)~~

It is fairly common to just put the dist HTML into a an Android WebView also. This is probably our best bet.

**Comment by jackschedel** [comment]
official median build is now in the readme.
https://median.co/share/exnwbx
(gonative got renamed to median, but is same thing)
