### ISSUE TITLE
Clicking "Stop Generating" before response receipt doesn't abort request

### ISSUE THREAD

**Issue by cheeseonamonkey** [jackschedel/gpt.koaladev.io#67]
If the timing is just right, the "Stop Generating" button can cause some wacky behavior - such as two responses being written at once to the same message, or the response stream getting appended to the last user message _(rather than a new assistant message)_.

---

Usually this happens when I quickly edit and re-send a message _(in under a second)_.

I think the reproduction trigger is pressing the "Stop Generating" button **_after_** the request is sent, but **_before_** a response stream has been received.

A simple fix might be to not show the button until the response has been received, although it might be better to also abort the request with the button.

Has anyone experienced this, and am I understanding correctly?

**Comment by jackschedel** [comment]
unable to reproduce - I might have too good of ping lol

**Comment by ghost** [comment]
Yeah I have experienced this back with the original version, it's quite rare, never got it with Koala (yet) though :)

**Comment by jackschedel** [comment]
unable to reproduce
