### ISSUE TITLE
Max context setting - minor bugs

### ISSUE THREAD

**Issue by cheeseonamonkey** [jackschedel/gpt.koaladev.io#72]
A couple small things to be ironed out with the max content setting calculations.

# max_token calculation

If I'm understanding [this](https://community.openai.com/t/clarification-for-max-tokens/19576/2) correctly, the API considers `max_tokens` to be the context and the response _combined_. So there shouldn't be a need to subtract the max context setting from the max token setting.

Currently we are calculating the parameter like this:
 `max_tokens = (maxTokenSetting - maxContextSetting)`

We should simply do this before each request:
- set the `maxTokenSetting` directly as the parameter in the request
- trim the messages by the `maxContextSetting`

<sup>Or, to calculate on the fly similar to this, we'd have to introduce a third setting, like I described in another issue:
 `max_tokens = (maxContextSettings - desiredMaxResponseSetting) ` *(with the maxTokenSetting still serving to cap this at a maximum)*

</sup>

---

# Other likely manifestations of this bug:

- Sometimes requests are sent with a `max_token` value that is too large to be allowed:

 >![image](https://github.com/jackschedel/KoalaClient/assets/54555500/f93d217c-7b5f-4348-bc81-1e4a054b5463)
 _(response is an error because the maximum value for `max_token` on gpt4 is ~8000)_.

**Comment by jackschedel** [comment]
Yardanico brought this up a few hours before you did lol, just in #34.
I just fixed this in 2.0.3.
