### ISSUE TITLE
(feature idea) Automatically set model according to settings & chat size

### ISSUE THREAD

**Issue by cheeseonamonkey** [jackschedel/gpt.koaladev.io#75]
# Automatically set model according to settings & chat size

### Proposed feature:
This would be best implemented as an optional _setting_, that a user could opt into. If enabled, the only models to choose from in the _chat config_ would be:
  - `gpt-3.5-turbo`
  - `gpt-4`

The token length models could then be automatically selected _only when required_, determined by these factors:
  - Chat config settings:
    - Max tokens
    - Max context
  - The size of the message <sup> _(for example, it is not necessary to use the `gpt-3.5-turbo-16k` model if you are well under the 4000 token limit for `gpt-3.5-turbo-16k`)_ </sup>

**Comment by jackschedel** [comment]
I agree that this should be implemented as an optional setting.

Low priority change for now until I have access to gpt4-32k xD

**Comment by jackschedel** [comment]
not planned - gpt4-turbo is so cheap and has so much context. individual defaults per folder (#27) is a better solution to this imo.

**Comment by jackschedel** [comment]
> not planned - gpt4-turbo is so cheap and has so much context. individual defaults per folder (#27) is a better solution to this imo.

could also use https://openrouter.ai/models/openrouter/auto
